### ISSUE TITLE
Initial setup: STAGING-CONFIG and PROD-CONFIG not defined

### ISSUE THREAD

**Issue by kanenathan213** [Lessig2016/pledge_service#2]
When I did  `npm install` , I got an error `Loading "Gruntfile.js" tasks...ERROR
 ReferenceError: STAGING_CONFIG is not defined`. To get the build working, in Gruntfile.js I defined new objects 

    var STAGING_CONFIG = {
      appName: 'staging-local-copy',
      appVersion: '1',
      hardCodeStripe: true,
      stripePublicKey: '',
      stripePrivateKey: '',
      productionPaypal: false,
    };

    var PROD_CONFIG = {
      appName: 'prod-local-copy',
      appVersion: '1',
      hardCodeStripe: true,
      stripePublicKey: '',
      stripePrivateKey: '',
      productionPaypal: false,
    };

This is a crummy workaround, but it was enough to get the build working.

To fix, should these config objects be defined in the repo itself?

**Comment by aaronlifshin** [comment]
Pushed a fix.  Retry.

**Comment by kanenathan213** [comment]
Great, master works now.
